http:
   port: "8081"

db:
   host: "localhost"
   user: "root"
   password: "Bandari@123"
   database: "dbname"
   port: "3306"
   
sf:
   user: "godha@home.com"
   password: "Bandari@123"
   key: "sq6UpDSJFOdUmqtiWcuXUK4TZ"
   